// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { Mulish } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
// const mulish = Mulish({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Marguerite",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={mulish.className}>{children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Mulish, Viga } from "next/font/google";
import "./globals.css";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-mulish",
  display: "swap",
});

const viga = Viga({
  subsets: ["latin"],
  weight: "400", 
  variable: "--font-viga",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Marguerite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mulish.variable} ${viga.variable}`}>
      <body>{children}</body>
    </html>
  );
}
